version: '3'

services:
  quasar:
    container_name: quasar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - quasar_backend_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - quasar_backend_network

networks:
  quasar_backend_network:
    driver: bridge
